jobs:

#RELEASE
      
  - name: manifest-ecs
    type: manifest
    steps:
      - IN: image1
        switch: off
      - IN: image2
      - IN: image3
       # versionNumber: 100
      - IN: real-tg1
      
  - name: manifest-gke
    type: manifest
    steps:
      - IN: image1
      - IN: image2
        switch: off
      - IN: image3
      - IN: real-tg2
      
  - name: manifest-tripub
    type: manifest
    steps:
      - IN: image1
      - IN: image2
      - IN: image3
        switch: off
      - IN: real-tg3
      
  - name: manifest-test
    type: manifest
    steps:
      - IN: image1
      - IN: real-dopts
      - IN: real-param
      - IN: real-scale1
      - IN: real-tg4      
      
  - name: testrp-ecsdeploy1
    type: deploy
    steps:
      - IN: manifest-test   
      #- IN: allpl-dopts2invalid
      - IN: real-param1
      - IN: real-scale1
      - IN: real-ecscluster
      - TASK: managed
        deployMethod: bluegreen
  
 # - name: testrp-ecsdeploy2
  #  type: deploy
   # steps:
    #  - IN: manifest-test   
      #- IN: allpl-dopts2invalid
     # - IN: real-param1
      #- IN: real-scale1
      #- IN: real-ecscluster
      #- TASK: managed
     #   deployMethod: replace
            
  - name: release-betaecs
    type: release
    steps:
      - IN: version-betaecs
      - IN: manifest-ecs
      - TASK: managed
        bump: beta
        
  - name: release-betagke
    type: release
    steps:
      - IN: version-betagke
      - IN: manifest-gke
      #- IN: test-time-3
      - TASK: managed
        bump: beta
        
  - name: release-betatripub
    type: release
    steps:
      - IN: version-betatripub
      - IN: manifest-tripub
      - TASK: managed
        bump: beta
        
  - name: beta-ecsdeploytest
    type: deploy
    steps:
      - IN: release-betaecs
      - IN: allpl-dopts
      - IN: allpl-ecscluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: beta-gkedeploy
    type: deploy
    steps:
      - IN: release-betagke
      - IN: allpl-dopts
      - IN: allpl-gkecluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: beta-tripubdeploy
    type: deploy
    steps:
      - IN: release-betatripub
       # switch: off
      - IN: allpl-dopts
      - IN: allpl-tripubcluster
        
  - name: dailyrelease-prod
    type: release
    steps:
      - IN: version-prodall
        #versionName: testrelease
      - IN: beta-ecsdeploy
      - IN: beta-gkedeploy
      - IN: beta-tripubdeploy
      - IN: timedailyprod-release
      - TASK: managed
        bump: patch
    flags:
      - dailyprod-release
    # on_start:
    #   - NOTIFY: allpl-email
    #   - NOTIFY: allpl-slack
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: majorrelease-prod
    type: release
    steps:
      - IN: version-prodall
        #versionName: testrelease
      - IN: dailyrelease-prod
      - IN: timemajorprod-release
      - TASK: managed
        bump: major
    flags:
      - majorprod-release
    # on_start:
    #   - NOTIFY: allpl-email
    #   - NOTIFY: allpl-slack
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  
