jobs:
      
  - name: tpm-release
    type: release
    steps:
      - IN: tpm-version
        #versionName: testrelease
      - TASK: managed
        bump: major
        
#MANIFESTS
      
  - name: tpm-manifest1
    type: manifest
    steps:
      - IN: fl-image1
       # versionNumber: 100
      - IN: tpm-tg1
      
  - name: tpm-manifest3multiimg
    type: manifest
    steps:
      - IN: fl-image6entrypoint
      - IN: fl-image7workingdir
     # - IN: flecs-dopts4
      #  applyTo:
        #  - fl-image6entrypoint
      - IN: tpm-tg3
      
#   - name: fl-manifest3env
#     type: manifest
#     steps:
#       - IN: fl-image5env
#       - IN: fl-params1
#       - IN: fl-params2
#       - IN: fl-tg3
      
#   - name: fl-manifest4entrypoint
#     type: manifest
#     steps:
#       - IN: fl-image6entrypoint
#       - TASK: managed
#       - IN: fl-tg4
      
#   - name: fl-manifest5driftking
#     type: manifest
#     steps:
#       - IN: fl-image7workingdir
#       - IN: fl-tg5
#       - TASK: managed
  
#   - name: fl-manifest6redismftomf
#     type: manifest
#     steps:
#       - IN: fl-image8redis
#       - IN: fl-manifest1
#         switch: off
      
#   - name: fl-manifest7invalid
#     type: manifest
#     steps:
#       - IN: fl-image1
#       - IN: fl-dopts6invalid
#       - IN: fl-tg7
      
#   - name: fl-manifest8
#     type: manifest
#     steps:
#       - IN: fl-image9
#       - IN: fl-dopts6invalid
#       - IN: fl-tg8
      
# # DEPLOYMENTS 

#   - name: fl-ecsdeployup
#     type: deploy
#     steps:
#       - IN: fl-manifest1
#       - IN: fl-ecscluster
#       - TASK: managed
#         deployMethod: upgrade
      
#   #- name: fl-ecsdeploybg
#   # type: deploy
#     #steps:
#     # - IN: fl-manifest4entrypoint
#       #- IN: flecs-dopts4
#       #- IN: fl-ecscluster
      
#   - name: fl-ecsdeployupmftomf
#     type: deploy
#     steps:
#       - IN: fl-manifest6redismftomf
#       - IN: fl-ecscluster
#       - TASK: managed
#         deployMethod: upgrade
        
#   - name: fl-ecsdeploybginvalid
#     type: deploy
#     steps:
#       - IN: fl-manifest7invalid
#       - IN: fl-ecscluster
      
  # - name: fl-ecsdeployuppm6436
  #   type: deploy
  #   steps:
  #     - IN: fl-manifest8
  #     - IN: fl-ecscluster
  #     - TASK: managed
  #       deployMethod: upgrade
      
  #- name: fl-tpdeployup
   # type: deploy
    #steps:
     # - IN: fl-manifest1
      #- IN: fltp-dopts1
      #- IN: fl-tripubcluster
    #  - TASK: managed
#     #   deployMethod: upgrade
      
  - name: tpm-ecsdeploybg2
    type: deploy
    steps:
    #  - IN: tpm-manifest1
      - IN: tpm-manifest3multiimg
      - IN: fl-ecscluster
      
 # - name: fl-gkedeployup
  #  type: deploy
   # steps:
    #  - IN: fl-manifest1
      #- IN: flgke-dopts3
     # - IN: fl-gkecluster
      #- TASK: managed
       # deployMethod: upgrade
      
  #- name: fl-gkedeploybg
   # type: deploy
    #steps:
     # - IN: fl-manifest5driftking
    #  - IN: flgke-dopts3
     # - IN: fl-gkecluster
      
 # - name: fl-dcldeploy
  #  type: deploy
   # steps:
    #  - IN: fl-manifest10deployall
     # - IN: fl-dclcluster
        
#  - name: fl-ddcdeploy
 #   type: deploy
  #  steps:
   #   - IN: fl-manifest10deployall
    #  - IN: fl-ddccluster
      
#runSh
  # - name: fl-inrunsh
  #   type: runSh
  #   steps:
  #     - IN: fl-sample-script1
  #       versionName: "149dc247602ba40192703b5fe0a1bfae01bd8490"
  #     - IN: fl-tg2
  #     - IN: fl-img1
  #     - IN: fl-man1
  #     - TASK:
  #     #  - script: ls
  #     # - script: ./IN/fl-sample-script/gitRepo/echo.sh
  #       - script: sudo apt-get install tree
  #       - script: tree -F IN
  #       - script: cat IN/fl-man1/integration.json
  #     #  - script: export versionName=$(cat ./IN/fl-img1/version.json | jq -r '.version.versionName')
  #       - script: . IN/fl-sample-script1/gitRepo/echo.sh
        
  # - name: fl-inrunsh2
  #   type: runSh
  #   steps:
  #     - IN: fl-sample-script2
  #     - IN: fl-tg6
  #     - TASK:
  #       - script: ls
  #       - script: ./IN/fl-sample-script2/gitRepo/echo.sh
