triggers:
   - name: real-tg1
     type: trigger
     version:
       counter: 0
       
   - name: real-tg2
     type: trigger
     version:
       counter: 0
       
   - name: real-tg3
     type: trigger
     version:
       counter: 0
       
   - name: real-tg4
     type: trigger
     version:
       counter: 0
