jobs:

#RELEASE

  - name: allpl-release
    type: release
    steps:
      - IN: allpl-version
        #versionName: testrelease
      - TASK: managed
        bump: beta
      - IN: allpl-tg3
    flags:
      - release_allpl
    on_start:
      - NOTIFY: allpl-email
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
#MANIFESTS
      
  - name: allpl-manifest1
    type: manifest
    steps:
      - IN: allpl-image1
       # versionNumber: 100
      - IN: allpl-tg1
    on_start:
      - NOTIFY: allpl-email
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  # - name: allpl-manifest2multiimg
  #   type: manifest
  #   steps:
  #     - IN: fl-image2
  #     - IN: fl-image7workingdir
  #     - IN: fl-dopts
  #       applyTo:
  #         - fl-image2
  #     - IN: fl-tg2
      
      
  - name: allpl-tpdeploybg
    type: deploy
    steps:
      - IN: allpl-manifest1
        switch: off
      - IN: allpl-dopts
      - IN: allpl-tripubcluster
    on_start:
      - NOTIFY: allpl-email
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: allpl-ddcdeploy
    type: deploy
    steps:
      - IN: allpl-manifest1
        switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-ddccluster
    on_start:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: allpl-dcldeploy
    type: deploy
    steps:
      - IN: allpl-manifest1
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-dclcluster
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: allpl-ecsdeployup1
    type: deploy
    steps:
      - IN: allpl-manifest1
        switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-ecscluster
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: allpl-gkedeployup1
    type: deploy
    steps:
      - IN: allpl-manifest1
        switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-gkecluster
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
