jobs:

#RELEASE

  - name: fl-release
    type: release
    steps:
      - IN: fl-version
        #versionName: testrelease
      - TASK: managed
        bump: beta
      - IN: fl-tg3
    flags:
      - release_flmaster
      
#MANIFESTS
      
  - name: fl-manifest1
    type: manifest
    steps:
      - IN: fl-image1
       # versionNumber: 100
      - IN: fl-tg1
      
  - name: fl-manifest2multiimg
    type: manifest
    steps:
      - IN: fl-image2
      - IN: fl-image7workingdir
      - IN: fl-dopts
        applyTo:
          - fl-image2
      - IN: fl-tg2
      
      
  #- name: fl-tpdeployup
   # type: deploy
    #steps:
     # - IN: fl-manifest1
      #- IN: fltp-dopts1
      #- IN: fl-tripubcluster
    #  - TASK: managed
     #   deployMethod: upgrade
      
  - name: fl-tpdeploybg1
    type: deploy
    steps:
      - IN: fl-manifest1
      - IN: fl-manifest2multiimg
        switch: off
      - IN: fl-dopts
      - IN: fl-tripubcluster
      
  - name: fl-ecsdeploybg1
    type: deploy
    steps:
      - IN: fl-manifest1
      - IN: fl-manifest2multiimg
        switch: off
      - IN: fl-dopts
      - IN: fl-ecscluster
      
