triggers:
   - name: allpl-tg1
     type: trigger
     version:
       counter: 1
       
   - name: allpl-tg2
     type: trigger
     version:
       counter: 0
       
   - name: allpl-tg3
     type: trigger
     version:
       counter: 3
       
   - name: allpl-tg4
     type: trigger
     version:
       counter: 0
