jobs:

#RELEASE

  - name: allpl-release1t
    type: release
    steps:
      - IN: allpl-versiont
        #versionName: testrelease
      - TASK: managed
        bump: beta
      - IN: allpl-tg3t
    flags:
      - release_allpl
    on_start:
      - NOTIFY: allpl-emailt
      #- NOTIFY: allpl-irc
    on_success:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
      #- NOTIFY: allpl-irc
      
#MANIFESTS
      
  - name: allpl-manifest1t
    type: manifest
    steps:
      - IN: allpl-image1t
       # versionNumber: 100
      - IN: allpl-tg1t
    on_start:
      - NOTIFY: allpl-emailt
    on_success:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
      
  - name: allpl-manifest2invalidtagt
    type: manifest
    steps:
      - IN: allpl-image3invalidtagt
       # versionNumber: 100
      - IN: allpl-tg2t
      
  - name: allpl-manifest3invalidformatt
    type: manifest
    steps:
      - IN: allpl-image4invalidformatt
       # versionNumber: 100
      - IN: allpl-tg3t
      
  - name: allpl-manifest4invalidrepott
    type: manifest
    steps:
      - IN: allpl-image2invalidimgt
       # versionNumber: 100
      - IN: allpl-tg3t
      
  - name: allpl-manifest5t
    type: manifest
    steps:
      - IN: allpl-image1t
        #versionNumber: 1000
      - IN: allpl-tg1t
      
  # - name: allpl-manifest2multiimg
  #   type: manifest
  #   steps:
  #     - IN: fl-image2
  #     - IN: fl-image7workingdir
  #     - IN: fl-dopts
  #       applyTo:
  #         - fl-image2
  #     - IN: fl-tg2
      
  - name: testallpl-tpdeploybg1t
    type: deploy
    steps:
      - IN: allpl-manifest5t
       # switch: off
      - IN: allpl-doptst
      - IN: allpl-tripubclustert
      - IN: allpl-image1t
        #versionNumber: 1000
      
    on_start:
      - NOTIFY: allpl-emailt
    on_success:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
    on_failure:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
      
  - name: testallpl-ddcdeploy1t
    type: deploy
    steps:
      - IN: allpl-manifest5t
       # switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-doptst
      - IN: allpl-ddcclustert
    on_start:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
    on_success:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
    on_failure:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
      
  - name: testallpl-dcldeploy1t
    type: deploy
    steps:
      - IN: allpl-manifest5t
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-doptst
      - IN: allpl-dclclustert
    on_success:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
    on_failure:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
      
  - name: testallpl-ecsdeployup11t
    type: deploy
    steps:
      - IN: allpl-manifest5t
      #  switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-doptst
      - IN: allpl-ecsclustert
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
    on_failure:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
      
  - name: testallpl-gkedeployup11t
    type: deploy
    steps:
      - IN: allpl-manifest5t
       # switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-doptst
      - IN: allpl-gkeclustert
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
    on_failure:
      - NOTIFY: allpl-emailt
      - NOTIFY: allpl-slackt
      
  - name: testY1t
    type: runSh
    steps:
      - IN: allpl-sample-scriptt
      # versionName: testsha
      - IN: allpl-tg2t
      - TASK:
        - script: ls
        - script: ./IN/allpl-sample-scriptt/gitRepo/echo.sh
    on_start:
      - NOTIFY: allpl-slackt
      - NOTIFY: allpl-emailt
    on_success:
      - NOTIFY: allpl-slackt
      - NOTIFY: allpl-emailt
      - script: echo 'infra test'
      - script: echo 'newtesting success'
    on_failure:
      - script: echo 'testing1 failure'
      - script: echo 'failure runSh'
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
      
  - name: testY2t
    type: runSh
    steps:
      #- IN: allpl-sample-script
      # versionName: testsha
      - IN: allpl-tg2t
      - TASK:
        - script: ls

      
  - name: INtestt
    type: runSh
    steps:
      - IN: allpl-sample-scriptt
        versionNumber: 2
      # versionName: testsha
      - IN: allpl-tg2t
      - IN: testY1t
      - TASK:
        - script: ls
        - script: ./IN/allpl-sample-scriptt/gitRepo/echo.sh
  # - name: outrunsh
  #   type: runSh
  #   steps:
  #     - TASK:
  #       - script: "mkdir -p /build/state/" # creating directory 
  #       - script: "touch /build/state/allpl-image1.env" # touch will create new empty file with timestamp
  #       - script: "echo 'Hello'"
  #     # - script: "echo 'versionName=latest' >>  /build/state/rs-img1.env" # this will be adding in the file mongo-image.env
  #       #- script: "echo 'anotherProperty=foo' >>  /build/state/rs-img1.env" # next line will be this in the file mongo-image.env
  #     - OUT: allpl-image1
  #     - IN: allpl-tg2
       
  # - name: inrunsh2
  #   type: runSh
  #   steps:
  #     - IN: allpl-sample-script
  #     # versionName: testsha
  #     - IN: allpl-tg2
  #     - TASK:
  #       - script: ./IN/allpl-sample-script/gitRepo/echo.sh
      
  # - name: allpl-gkedeployup2
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest2invalidtag
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-gkedeploybg1
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest2invalidtag
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
      
  # - name: allpl-ecsdeployup2
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest3invalidformat
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-ecsdeploybg1
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest3invalidformat
  #     - IN: allpl-dopts
  #     - IN: allpl-ecscluster
      
  # - name: allpl-gkedeployup3
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest3invalidformat
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-gkedeploybg2
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest3invalidformat
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
      
  # - name: allpl-ecsdeployup3
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest2invalidtag
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-ecsdeploybg4
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest2invalidtag
  #     - IN: allpl-dopts
  #     - IN: allpl-ecscluster
      
  # - name: allpl-gkedeployup4
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest4invalidrepo
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-gkedeploybg3
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest4invalidrepo
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
      
  # - name: allpl-ecsdeployup4
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest4invalidrepo
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-ecsdeploybg5
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest4invalidrepo
  #     - IN: allpl-dopts
  #     - IN: allpl-ecscluster
