jobs:

#RELEASE

  - name: allpl-release
    type: release
    steps:
      - IN: allpl-version
        #versionName: testrelease
      - TASK: managed
        bump: beta
      - IN: allpl-tg3
    flags:
      - release_allpl
    on_start:
      - NOTIFY: allpl-email
      #- NOTIFY: allpl-irc
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      #- NOTIFY: allpl-irc
      
#MANIFESTS
      
  - name: allpl-manifest1
    type: manifest
    steps:
      - IN: allpl-image1
       # versionNumber: 100
      - IN: allpl-tg1
    on_start:
      - NOTIFY: allpl-email
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: allpl-manifest2invalidtag
    type: manifest
    steps:
      - IN: allpl-image3invalidtag
       # versionNumber: 100
      - IN: allpl-tg2
      
  - name: allpl-manifest3invalidformat
    type: manifest
    steps:
      - IN: allpl-image4invalidformat
       # versionNumber: 100
      - IN: allpl-tg3
      
  - name: allpl-manifest4invalidrepo
    type: manifest
    steps:
      - IN: allpl-image2invalidimg
       # versionNumber: 100
      - IN: allpl-tg3
      
  # - name: allpl-manifest2multiimg
  #   type: manifest
  #   steps:
  #     - IN: fl-image2
  #     - IN: fl-image7workingdir
  #     - IN: fl-dopts
  #       applyTo:
  #         - fl-image2
  #     - IN: fl-tg2
      
      
  - name: allpl-tpdeploybg
    type: deploy
    steps:
      - IN: allpl-manifest1
       # switch: off
      - IN: allpl-dopts
      - IN: allpl-tripubcluster
    on_start:
      - NOTIFY: allpl-email
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: allpl-ddcdeploy
    type: deploy
    steps:
      - IN: allpl-manifest1
       # switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-ddccluster
    on_start:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: allpl-dcldeploy
    type: deploy
    steps:
      - IN: allpl-manifest1
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-dclcluster
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: allpl-ecsdeployup1
    type: deploy
    steps:
      - IN: allpl-manifest1
      #  switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-ecscluster
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: allpl-gkedeployup1
    type: deploy
    steps:
      - IN: allpl-manifest1
       # switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-gkecluster
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: inrunsh
    type: runSh
    steps:
      - IN: allpl-sample-script
      # versionName: testsha
      - IN: allpl-tg2
      - TASK:
        - script: ls
        - script: ./IN/allpl-sample-script/gitRepo/echo.sh
    on_start:
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
    on_success:
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
      - script: echo 'infra test'
      - script: echo 'newtesting success'
    on_failure:
      - script: echo 'testing1 failure'
      - script: echo 'failure runSh'
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
      
  - name: inrunshtest1
    type: runSh
    steps:
      - IN: allpl-sample-script
      # versionName: testsha
      - IN: allpl-tg2
      - TASK:
        - script: ls
        - script: ./IN/allpl-sample-script/gitRepo/echo.sh
      
  # - name: inrunsh2
  #   type: runSh
  #   steps:
  #     - IN: allpl-sample-script
  #     # versionName: testsha
  #     - IN: allpl-tg2
  #     - TASK:
  #       - script: ./IN/allpl-sample-script/gitRepo/echo.sh
      
  # - name: allpl-gkedeployup2
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest2invalidtag
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-gkedeploybg1
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest2invalidtag
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
      
  # - name: allpl-ecsdeployup2
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest3invalidformat
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-ecsdeploybg1
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest3invalidformat
  #     - IN: allpl-dopts
  #     - IN: allpl-ecscluster
      
  # - name: allpl-gkedeployup3
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest3invalidformat
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-gkedeploybg2
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest3invalidformat
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
      
  # - name: allpl-ecsdeployup3
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest2invalidtag
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-ecsdeploybg4
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest2invalidtag
  #     - IN: allpl-dopts
  #     - IN: allpl-ecscluster
      
  # - name: allpl-gkedeployup4
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest4invalidrepo
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-gkedeploybg3
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest4invalidrepo
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
      
  # - name: allpl-ecsdeployup4
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest4invalidrepo
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-ecsdeploybg5
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest4invalidrepo
  #     - IN: allpl-dopts
  #     - IN: allpl-ecscluster
